import ServiceContextProvider from "@/context/ServiceContext"

export const metadata = {
  title: 'Evolve Designs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ServiceContextProvider>
            {children}
        </ServiceContextProvider>
        </body>
    </html>
  )
}